server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: localhost
  client:
    # This is the server, so it doesn't need to register itself or fetch its own data
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Self-preservation prevents Eureka from removing services if network issues occur
    enable-self-preservation: true