server:
  port: 8000 # This is the port your React app will talk to

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive # Gateway is built on Project Reactor
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true
      # Manual Routes with Security Filters
      routes:
        - id: student-service
          uri: lb://student-service 
          predicates:
            - Path=/student/**
          filters:
            - AuthenticationFilter # Protects all student endpoints

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/** 
          filters:
            - AuthenticationFilter # Protects all department endpoints

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/** # No filter here: /register and /token must be public

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/