server:
  port: 8081

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/cms_student_db
    username: root 
    password: Sprince1* 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # This helps the gateway identify the service by a specific name
    prefer-ip-address: true